version: "3.9"

services:
  api:
    build: .
    container_name: eora_ai_assistant_bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: pdm run python src/main.py
